apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
  namespace: ticketing
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: robertst98/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - name: http
              containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
  namespace: ticketing
  labels:
    app: payments
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 4003
      targetPort: 4003
