apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  namespace: ticketing
  labels:
    app: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: robertst98/tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - name: http
              containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
  namespace: ticketing
  labels:
    app: tickets
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 4001
      targetPort: 4001
